### PR TITLE
Force nimcache to be under pmgen/ (in case user has some other default

### PR DESCRIPTION
**Pull request by c-blake**
in their home nim.cfg).

### CODE REVIEW

**Comment by c-blake** [comment]
(An alternate approach might be to leave the user's nimcache alone, but then you'd need to extract that and use it in a few places...Just forcing it seemed simplest.)

**Comment by jboy** [comment]
Great, thanks!  Just out of curiosity, what is the default in your home "nim.cfg"?  :)

**Comment by c-blake** [comment]
I like to put things under /tmp/$LOGNAME/cache/nim partly to keep them out of the way of things like version control systems (or just 'ls') and partly since I have a /tmp that is a tmpfs on Linux (a ram file system) which is faster/swept on reboots.  Other XDG_CACHE stuff goes in /tmp/$LOGNAME/cache, too.  Just my personal setup for personal taste reasons.

To get your code to work I also had to put in some symbolic links under /usr/include/pythonX.Y to /usr/lib/pythonX.Y/site-packages/numpy/core/include/numpy.  (For that issue, I think a better approach is extracting the right site-packages include path and putting it compile lines, but I didn't yet have time to figure out how to do that in pmgen).

Anyway, after those two fixes - one in your pymod tree already merged and one very much out of tree - I got all 6 of your tests to run on a Gentoo Linux (rolling release) with gcc-5.2.0 and both python-2.7.10 and python-3.5.0.

**Comment by jboy** [comment]
Thanks for your perseverance to get the code to work!

Can you elaborate on the need for symlinks?  Are you saying you had to create links, inside the directories `/usr/include/pythonX.Y`, that point to `/usr/lib/pythonX.Y/site-packages/numpy/core/include/numpy`?  What was Pymod doing wrong?

I've tried to be as cross-platform (at least, cross-UNIX/Linux) as possible in my specification of include paths & libraries to link.  (I was lazy about the Python headers & library, but I paid off that technical debt, with interest, when I fixed that about 24 hours ago, to be Python3-compatible.)

And thanks also for your success info (and for compiling & running all 6 of the tests!).  Would you be able to copy-paste the output of the following commands?

* `uname -osm`
* `python --version`
* `nim --version 2>&1 | head -1`
* `gcc --version | head -1`
* `python -c 'import numpy ; print("Numpy %s" % numpy.__version__)'`
* `date`

**Comment by c-blake** [comment]
Sure.  By default, at least on Gentoo, but I think more broadly, the numpy headers go into the python-lib-root/site-packages/numpy/core/include directory, but that means you need -I things in the C compiler toolchain to point there.  I tried some minimal thing in pymod-extensions.cfg but it didn't quite take - maybe I didn't use the right section/etc.  I could see what was amiss from the compile lines.  So I just made the symlinks out of expediency so that the single -I/usr/include/pythonX.Y was enough to support the #include "numpy/whatever".  That would honestly be a good thing for NumPy/other extension packages to do anyway so that any extension could be built just with the single -I flag.

As for your ITWORKS addition, there are kinda 2 since py2 & py3 and those versions are as already mentioned, but here you go.

py2:
Linux x86_64 GNU/Linux
Python 2.7.10
Nim Compiler Version 0.12.1 (2015-11-12) [Linux: amd64]
gcc (Gentoo 5.2.0 p1.0, pie-0.6.3) 5.2.0
Numpy 1.10.1
Fri Nov 13 09:36:12 EST 2015

py3:
Linux x86_64 GNU/Linux
Python 3.5.0
Nim Compiler Version 0.12.1 (2015-11-12) [Linux: amd64]
gcc (Gentoo 5.2.0 p1.0, pie-0.6.3) 5.2.0
Numpy 1.10.1
Fri Nov 13 09:37:15 EST 2015

**Comment by jboy** [comment]
Firstly, thanks for your `ITWORKS` success info -- that's awesome.

Regarding your point about the Numpy headers:  It took me a while to understand what you meant, but I think I get it now.

It took me a while to get it, because on my Linux Mint (Ubuntu) system, there are already symlinks from `/usr/include` into those deep directories:

```
$ cd /usr/include
$ ls -l numpy
lrwxrwxrwx 1 root root 55 Dec 25  2014 numpy -> ../lib/python2.7/dist-packages/numpy/core/include/numpy
$ ls -l python2.7/numpy
lrwxrwxrwx 1 root root 58 Dec 25  2014 python2.7/numpy -> ../../lib/python2.7/dist-packages/numpy/core/include/numpy
$ ls -l python3.4/numpy
lrwxrwxrwx 1 root root 56 Sep 18  2014 python3.4/numpy -> ../../lib/python3/dist-packages/numpy/core/include/numpy
```
Maybe these symlinks are created by some Debian/Ubuntu `-dev` package?

But!  Then I realised that those symlinks are pointing to the (dpkg-managed) installations in `/usr`, rather than my own newer (compiled-from-source) installations in `/usr/local`.  D'oh!

So yeah, something that should be fixed in general.

As you say, it would be a tidy solution if it could be configured in `pymod-extensions.cfg`.  (I'm embarrassed to say it, but reading from `pymod-extensions.cfg` isn't actually implemented yet!  It was something that I anticipated would be a useful escape-hatch for obscure or problematic configuration options.  But I ended up solving some of the options in other ways -- like the `[Python]` section, for example: As of 24 hours ago, I now use the system's `python-config` script instead.)

**Comment by c-blake** [comment]
Yeah...It's part of the packaging magic of whatever you're using.  As I said, I don't even think it's unreasonable packaging magic, but in terms of pmgen and portability you do probably need to put in a -I<py-site-packages>/numpy/core/include (either in your pymod-extensions.cfg or wherever it is now).  It sounds like that setup would also work on your own distro but just be portable by not relying on the packaging magic.

There may be some more canonical way to get that root, but something like this has worked for me in py2/py3 for like more than 5 years:
```
[ d for d in sys.path if d.endswith("/site-packages") ][0]
```
So, you could even get it with a python -c "import sys; print <THE-ABOVE>" which you could run as a shell command in makefiles or whatever you like.

**Comment by jboy** [comment]
Thanks, that's a great suggestion!

I've given the issue some thought, and I've actually taken your idea a step further: As you can see in this commit db3e786cbe1a7f21d0e7a47a3eb80bce4af7e002 , I've decided to use the Python instance that's executing `pmgen.py` to determine the Numpy installation settings.

First, I actually *test* that Numpy is installed (rather than simply assuming it is, as I did previously) by attempting to `import numpy`.

Then, I access Numpy's ``numpy.__path__`` to get the Numpy installation paths.  On my system, this returns:
```
['/usr/local/lib/python2.7/site-packages/numpy']
```
for Python2, and:
```
['/usr/lib/python3/dist-packages/numpy']
```
for Python3.

I can then construct a correct Numpy include path from that, by joining `core/include` to the end of each path in that list (and testing that this newly-constructed path actually exists).

If it's not a hassle, would you be able to check that this works correctly for your system?

**Comment by c-blake** [comment]
Sure.  I deleted those symlinks and your new approach worked fine.  To avoid repeating myself and achieve some parallelism on my 6 core box, I captured my shell history into a little script.  I'll just paste it here for reference.  It surely could be re-done in python itself instead of shell to get maybe Windows portability (but I'm not sure how much other stuff would really need to change for that, pmgen-wide), and there could be other unit test framework applications instead of this.  But this was trivial to do and seemed possibly worth sharing with you/the world:
```
#!/bin/sh
banner() {
  echo '########################################'
}

for py in python2 python3 pypy; do
  ( cd 000-helloWorld; set -e
    $py ../../pmgen.py greeting
    banner
    $py test_hello_world.py
    banner
    rm -rf pmgen *.so ) > test.000 2>&1 &

  ( cd 001-miscExamples; set -e
    $py ../../pmgen.py testPymod.nim
    banner
    $py -c 'import testpymod1, testpymod2, testpymod3'
    banner
    rm -rf pmgen *.so ) > test.001 2>&1 &

  ( cd 002-testRefcount; set -e
    $py ../../pmgen.py refcount.nim
    banner
    $py test_refcount.py
    banner
    rm -rf pmgen *.so ) > test.002 2>&1 &

  ( cd 003-testCopying; set -e
    $py ../../pmgen.py copying.nim
    banner
    $py test_copying.py
    banner
    rm -rf pmgen *.so ) > test.003 2>&1 &

  ( cd 004-returnTuple; set -e
    $py ../../pmgen.py returntuple.nim
    banner
    $py test_returntuple.py
    banner
    rm -rf pmgen *.so ) > test.004 2>&1 &

  ( cd 005-doResize; set -e
    $py ../../pmgen.py doresize.nim
    banner
    $py test_doresize.py
    banner
    rm -rf pmgen *.so ) > test.005 2>&1 &

    wait
    cat test.0* > test.$py
    rm -f test.0*
done
```

**Comment by c-blake** [comment]
(Also, nothing works with the pypy iteration, but I don't have the pypy Numpy installed at the moment.)

**Comment by jboy** [comment]
Thanks for checking that the new approach works. :)

It's a shame that [PyPy requires a special Numpy](http://pypy.org/download.html#installing-numpy).

And thanks for the unit test script!  I've actually been intending to do the tests properly -- ie, as actual *tests*, with a "run all" script in the root of the `tests` subdirectory.  Would you happen to have any recommendations for a Python unit test framework that would allow a Nim compilation step before each test?

**Comment by c-blake** [comment]
I agree it would be nicer if the pypy version of numpy could be merged into mainline..maybe someday.  Pypy has become a pretty viable alternative Python for a while now and Gentoo and probably others makes it pretty easy to deal with multiple python incarnations installed all at once.

As for unit test recommendations..Nah.  No particular recommendations per se.  As an observation, "nose" seems popular in the Python world and I think numpy.test uses that, but I don't know if it has all the hooks you want/need.  There are many ways to skin this cat depending on what dependencies you want.  A top-level 'make test' with a diff of expected output can also get the job done..or something like that script. :)

**Pull request merged**
